server:
  port: 8181
  servlet:
    context-path: /app
spring:
  jackson:
    default-property-inclusion: non_null  # Исключить null значения
    property-naming-strategy: SNAKE_CASE # Использовать snake_case для полей
    date-format: yyyy-MM-dd             # Формат дат
    time-zone: UTC
  datasource:
    username: root
    password: Arces2023!!
    url: jdbc:mysql://localhost:3306/app_arces
    driver-class-name: com.mysql.cj.jdbc.Driver
jpa:
  show-sql: true
  hibernate:
    ddl-auto: none
logging:
  level:
    com:
      arces:
        app_arces: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"